apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: football-app
  namespace: games
  labels:
    app: football-app
    role: front
spec:
  replicas: 2
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2 # maxSurge is the maximum number of new pods that will be created at a time
        maxUnavailable: 1 # maxUnavailable is the maximum number of old pods that will be deleted at a time 
  template:
    metadata:
      labels:
        app: football-app
        role: front
    spec:
      containers:
        - name: football-app
          image: "arindambanerjee/game-app:v1"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          livenessProbe:
                httpGet:
                    path: /
                    port: 8080
                initialDelaySeconds: 15
                timeoutSeconds: 30 
          readinessProbe:
                httpGet:
                    path: /
                    port: 8080
                initialDelaySeconds: 15
                timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: football-app
  namespace: games  
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http 
  selector:
    app: football-app
    role: front
  type: LoadBalancer
